#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hauli
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="C:\\Users\\Cubio\\Dropbox\\TOL\\Projekti 2\\Git\\Hauli\\Hauli\\HauliDB.sdf")]
	public partial class HauliDBContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertAsetukset(Asetukset instance);
    partial void UpdateAsetukset(Asetukset instance);
    partial void DeleteAsetukset(Asetukset instance);
    partial void InsertEraluettelo(Eraluettelo instance);
    partial void UpdateEraluettelo(Eraluettelo instance);
    partial void DeleteEraluettelo(Eraluettelo instance);
    partial void InsertJoukkue(Joukkue instance);
    partial void UpdateJoukkue(Joukkue instance);
    partial void DeleteJoukkue(Joukkue instance);
    partial void InsertOsallistuja(Osallistuja instance);
    partial void UpdateOsallistuja(Osallistuja instance);
    partial void DeleteOsallistuja(Osallistuja instance);
    partial void InsertSarja(Sarja instance);
    partial void UpdateSarja(Sarja instance);
    partial void DeleteSarja(Sarja instance);
    partial void InsertSeura(Seura instance);
    partial void UpdateSeura(Seura instance);
    partial void DeleteSeura(Seura instance);
    #endregion
		
		public HauliDBContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HauliDBContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HauliDBContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HauliDBContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Asetukset> Asetukset
		{
			get
			{
				return this.GetTable<Asetukset>();
			}
		}
		
		public System.Data.Linq.Table<Eraluettelo> Eraluettelo
		{
			get
			{
				return this.GetTable<Eraluettelo>();
			}
		}
		
		public System.Data.Linq.Table<Joukkue> Joukkue
		{
			get
			{
				return this.GetTable<Joukkue>();
			}
		}
		
		public System.Data.Linq.Table<Osallistuja> Osallistuja
		{
			get
			{
				return this.GetTable<Osallistuja>();
			}
		}
		
		public System.Data.Linq.Table<Sarja> Sarja
		{
			get
			{
				return this.GetTable<Sarja>();
			}
		}
		
		public System.Data.Linq.Table<Seura> Seura
		{
			get
			{
				return this.GetTable<Seura>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute()]
	public partial class Asetukset : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _AsetuksetID;
		
		private string _Jarjestaja;
		
		private string _Tapahtuma;
		
		private string _Paikkakunta;
		
		private System.Nullable<int> _Radat;
		
		private System.Nullable<int> _Erankesto;
		
		private System.Nullable<System.DateTime> _Paiva1;
		
		private System.Nullable<System.DateTime> _Paiva2;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAsetuksetIDChanging(int value);
    partial void OnAsetuksetIDChanged();
    partial void OnJarjestajaChanging(string value);
    partial void OnJarjestajaChanged();
    partial void OnTapahtumaChanging(string value);
    partial void OnTapahtumaChanged();
    partial void OnPaikkakuntaChanging(string value);
    partial void OnPaikkakuntaChanged();
    partial void OnRadatChanging(System.Nullable<int> value);
    partial void OnRadatChanged();
    partial void OnErankestoChanging(System.Nullable<int> value);
    partial void OnErankestoChanged();
    partial void OnPaiva1Changing(System.Nullable<System.DateTime> value);
    partial void OnPaiva1Changed();
    partial void OnPaiva2Changing(System.Nullable<System.DateTime> value);
    partial void OnPaiva2Changed();
    #endregion
		
		public Asetukset()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="asetuksetID", Storage="_AsetuksetID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int AsetuksetID
		{
			get
			{
				return this._AsetuksetID;
			}
			set
			{
				if ((this._AsetuksetID != value))
				{
					this.OnAsetuksetIDChanging(value);
					this.SendPropertyChanging();
					this._AsetuksetID = value;
					this.SendPropertyChanged("AsetuksetID");
					this.OnAsetuksetIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="jarjestaja", Storage="_Jarjestaja", DbType="NVarChar(100)")]
		public string Jarjestaja
		{
			get
			{
				return this._Jarjestaja;
			}
			set
			{
				if ((this._Jarjestaja != value))
				{
					this.OnJarjestajaChanging(value);
					this.SendPropertyChanging();
					this._Jarjestaja = value;
					this.SendPropertyChanged("Jarjestaja");
					this.OnJarjestajaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="tapahtuma", Storage="_Tapahtuma", DbType="NVarChar(100)")]
		public string Tapahtuma
		{
			get
			{
				return this._Tapahtuma;
			}
			set
			{
				if ((this._Tapahtuma != value))
				{
					this.OnTapahtumaChanging(value);
					this.SendPropertyChanging();
					this._Tapahtuma = value;
					this.SendPropertyChanged("Tapahtuma");
					this.OnTapahtumaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="paikkakunta", Storage="_Paikkakunta", DbType="NVarChar(100)")]
		public string Paikkakunta
		{
			get
			{
				return this._Paikkakunta;
			}
			set
			{
				if ((this._Paikkakunta != value))
				{
					this.OnPaikkakuntaChanging(value);
					this.SendPropertyChanging();
					this._Paikkakunta = value;
					this.SendPropertyChanged("Paikkakunta");
					this.OnPaikkakuntaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="radat", Storage="_Radat", DbType="Int")]
		public System.Nullable<int> Radat
		{
			get
			{
				return this._Radat;
			}
			set
			{
				if ((this._Radat != value))
				{
					this.OnRadatChanging(value);
					this.SendPropertyChanging();
					this._Radat = value;
					this.SendPropertyChanged("Radat");
					this.OnRadatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="erankesto", Storage="_Erankesto", DbType="Int")]
		public System.Nullable<int> Erankesto
		{
			get
			{
				return this._Erankesto;
			}
			set
			{
				if ((this._Erankesto != value))
				{
					this.OnErankestoChanging(value);
					this.SendPropertyChanging();
					this._Erankesto = value;
					this.SendPropertyChanged("Erankesto");
					this.OnErankestoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="paiva1", Storage="_Paiva1", DbType="DateTime")]
		public System.Nullable<System.DateTime> Paiva1
		{
			get
			{
				return this._Paiva1;
			}
			set
			{
				if ((this._Paiva1 != value))
				{
					this.OnPaiva1Changing(value);
					this.SendPropertyChanging();
					this._Paiva1 = value;
					this.SendPropertyChanged("Paiva1");
					this.OnPaiva1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="paiva2", Storage="_Paiva2", DbType="DateTime")]
		public System.Nullable<System.DateTime> Paiva2
		{
			get
			{
				return this._Paiva2;
			}
			set
			{
				if ((this._Paiva2 != value))
				{
					this.OnPaiva2Changing(value);
					this.SendPropertyChanging();
					this._Paiva2 = value;
					this.SendPropertyChanged("Paiva2");
					this.OnPaiva2Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute()]
	public partial class Eraluettelo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _EraluetteloID;
		
		private System.Nullable<int> _JuoksevaRataNro;
		
		private System.Nullable<int> _RataNro;
		
		private System.Nullable<int> _Kierros;
		
		private System.Nullable<int> _Era;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnEraluetteloIDChanging(int value);
    partial void OnEraluetteloIDChanged();
    partial void OnJuoksevaRataNroChanging(System.Nullable<int> value);
    partial void OnJuoksevaRataNroChanged();
    partial void OnRataNroChanging(System.Nullable<int> value);
    partial void OnRataNroChanged();
    partial void OnKierrosChanging(System.Nullable<int> value);
    partial void OnKierrosChanged();
    partial void OnEraChanging(System.Nullable<int> value);
    partial void OnEraChanged();
    #endregion
		
		public Eraluettelo()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="eraluetteloID", Storage="_EraluetteloID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int EraluetteloID
		{
			get
			{
				return this._EraluetteloID;
			}
			set
			{
				if ((this._EraluetteloID != value))
				{
					this.OnEraluetteloIDChanging(value);
					this.SendPropertyChanging();
					this._EraluetteloID = value;
					this.SendPropertyChanged("EraluetteloID");
					this.OnEraluetteloIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="juoksevaRataNro", Storage="_JuoksevaRataNro", DbType="Int")]
		public System.Nullable<int> JuoksevaRataNro
		{
			get
			{
				return this._JuoksevaRataNro;
			}
			set
			{
				if ((this._JuoksevaRataNro != value))
				{
					this.OnJuoksevaRataNroChanging(value);
					this.SendPropertyChanging();
					this._JuoksevaRataNro = value;
					this.SendPropertyChanged("JuoksevaRataNro");
					this.OnJuoksevaRataNroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="rataNro", Storage="_RataNro", DbType="Int")]
		public System.Nullable<int> RataNro
		{
			get
			{
				return this._RataNro;
			}
			set
			{
				if ((this._RataNro != value))
				{
					this.OnRataNroChanging(value);
					this.SendPropertyChanging();
					this._RataNro = value;
					this.SendPropertyChanged("RataNro");
					this.OnRataNroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="kierros", Storage="_Kierros", DbType="Int")]
		public System.Nullable<int> Kierros
		{
			get
			{
				return this._Kierros;
			}
			set
			{
				if ((this._Kierros != value))
				{
					this.OnKierrosChanging(value);
					this.SendPropertyChanging();
					this._Kierros = value;
					this.SendPropertyChanged("Kierros");
					this.OnKierrosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="era", Storage="_Era", DbType="Int")]
		public System.Nullable<int> Era
		{
			get
			{
				return this._Era;
			}
			set
			{
				if ((this._Era != value))
				{
					this.OnEraChanging(value);
					this.SendPropertyChanging();
					this._Era = value;
					this.SendPropertyChanged("Era");
					this.OnEraChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute()]
	public partial class Joukkue : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _JoukkueID;
		
		private string _Joukkue1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnJoukkueIDChanging(int value);
    partial void OnJoukkueIDChanged();
    partial void OnJoukkue1Changing(string value);
    partial void OnJoukkue1Changed();
    #endregion
		
		public Joukkue()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="joukkueID", Storage="_JoukkueID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int JoukkueID
		{
			get
			{
				return this._JoukkueID;
			}
			set
			{
				if ((this._JoukkueID != value))
				{
					this.OnJoukkueIDChanging(value);
					this.SendPropertyChanging();
					this._JoukkueID = value;
					this.SendPropertyChanged("JoukkueID");
					this.OnJoukkueIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="joukkue", Storage="_Joukkue1", DbType="NVarChar(100)")]
		public string Joukkue1
		{
			get
			{
				return this._Joukkue1;
			}
			set
			{
				if ((this._Joukkue1 != value))
				{
					this.OnJoukkue1Changing(value);
					this.SendPropertyChanging();
					this._Joukkue1 = value;
					this.SendPropertyChanged("Joukkue1");
					this.OnJoukkue1Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute()]
	public partial class Osallistuja : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _OsallistujaID;
		
		private int _Nro;
		
		private string _Nimi;
		
		private string _Sukunimi;
		
		private System.Nullable<int> _Kierros25;
		
		private System.Nullable<int> _Kierros50;
		
		private System.Nullable<int> _Kierros75;
		
		private System.Nullable<int> _Kierros100;
		
		private System.Nullable<int> _Kierros125;
		
		private System.Nullable<int> _KierrosRatkonta;
		
		private System.Nullable<int> _FinaaliKierros;
		
		private System.Nullable<int> _FinaaliRatkonta;
		
		private int _SeuraID;
		
		private System.Nullable<int> _JoukkueID;
		
		private System.Nullable<int> _SarjaID;
		
		private string _Era;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnOsallistujaIDChanging(int value);
    partial void OnOsallistujaIDChanged();
    partial void OnNroChanging(int value);
    partial void OnNroChanged();
    partial void OnNimiChanging(string value);
    partial void OnNimiChanged();
    partial void OnSukunimiChanging(string value);
    partial void OnSukunimiChanged();
    partial void OnKierros25Changing(System.Nullable<int> value);
    partial void OnKierros25Changed();
    partial void OnKierros50Changing(System.Nullable<int> value);
    partial void OnKierros50Changed();
    partial void OnKierros75Changing(System.Nullable<int> value);
    partial void OnKierros75Changed();
    partial void OnKierros100Changing(System.Nullable<int> value);
    partial void OnKierros100Changed();
    partial void OnKierros125Changing(System.Nullable<int> value);
    partial void OnKierros125Changed();
    partial void OnKierrosRatkontaChanging(System.Nullable<int> value);
    partial void OnKierrosRatkontaChanged();
    partial void OnFinaaliKierrosChanging(System.Nullable<int> value);
    partial void OnFinaaliKierrosChanged();
    partial void OnFinaaliRatkontaChanging(System.Nullable<int> value);
    partial void OnFinaaliRatkontaChanged();
    partial void OnSeuraIDChanging(int value);
    partial void OnSeuraIDChanged();
    partial void OnJoukkueIDChanging(System.Nullable<int> value);
    partial void OnJoukkueIDChanged();
    partial void OnSarjaIDChanging(System.Nullable<int> value);
    partial void OnSarjaIDChanged();
    partial void OnEraChanging(string value);
    partial void OnEraChanged();
    #endregion
		
		public Osallistuja()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="osallistujaID", Storage="_OsallistujaID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int OsallistujaID
		{
			get
			{
				return this._OsallistujaID;
			}
			set
			{
				if ((this._OsallistujaID != value))
				{
					this.OnOsallistujaIDChanging(value);
					this.SendPropertyChanging();
					this._OsallistujaID = value;
					this.SendPropertyChanged("OsallistujaID");
					this.OnOsallistujaIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="nro", Storage="_Nro", DbType="Int NOT NULL")]
		public int Nro
		{
			get
			{
				return this._Nro;
			}
			set
			{
				if ((this._Nro != value))
				{
					this.OnNroChanging(value);
					this.SendPropertyChanging();
					this._Nro = value;
					this.SendPropertyChanged("Nro");
					this.OnNroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="nimi", Storage="_Nimi", DbType="NVarChar(100)")]
		public string Nimi
		{
			get
			{
				return this._Nimi;
			}
			set
			{
				if ((this._Nimi != value))
				{
					this.OnNimiChanging(value);
					this.SendPropertyChanging();
					this._Nimi = value;
					this.SendPropertyChanged("Nimi");
					this.OnNimiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="sukunimi", Storage="_Sukunimi", DbType="NVarChar(100)")]
		public string Sukunimi
		{
			get
			{
				return this._Sukunimi;
			}
			set
			{
				if ((this._Sukunimi != value))
				{
					this.OnSukunimiChanging(value);
					this.SendPropertyChanging();
					this._Sukunimi = value;
					this.SendPropertyChanged("Sukunimi");
					this.OnSukunimiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="kierros25", Storage="_Kierros25", DbType="Int")]
		public System.Nullable<int> Kierros25
		{
			get
			{
				return this._Kierros25;
			}
			set
			{
				if ((this._Kierros25 != value))
				{
					this.OnKierros25Changing(value);
					this.SendPropertyChanging();
					this._Kierros25 = value;
					this.SendPropertyChanged("Kierros25");
					this.OnKierros25Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="kierros50", Storage="_Kierros50", DbType="Int")]
		public System.Nullable<int> Kierros50
		{
			get
			{
				return this._Kierros50;
			}
			set
			{
				if ((this._Kierros50 != value))
				{
					this.OnKierros50Changing(value);
					this.SendPropertyChanging();
					this._Kierros50 = value;
					this.SendPropertyChanged("Kierros50");
					this.OnKierros50Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="kierros75", Storage="_Kierros75", DbType="Int")]
		public System.Nullable<int> Kierros75
		{
			get
			{
				return this._Kierros75;
			}
			set
			{
				if ((this._Kierros75 != value))
				{
					this.OnKierros75Changing(value);
					this.SendPropertyChanging();
					this._Kierros75 = value;
					this.SendPropertyChanged("Kierros75");
					this.OnKierros75Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="kierros100", Storage="_Kierros100", DbType="Int")]
		public System.Nullable<int> Kierros100
		{
			get
			{
				return this._Kierros100;
			}
			set
			{
				if ((this._Kierros100 != value))
				{
					this.OnKierros100Changing(value);
					this.SendPropertyChanging();
					this._Kierros100 = value;
					this.SendPropertyChanged("Kierros100");
					this.OnKierros100Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="kierros125", Storage="_Kierros125", DbType="Int")]
		public System.Nullable<int> Kierros125
		{
			get
			{
				return this._Kierros125;
			}
			set
			{
				if ((this._Kierros125 != value))
				{
					this.OnKierros125Changing(value);
					this.SendPropertyChanging();
					this._Kierros125 = value;
					this.SendPropertyChanged("Kierros125");
					this.OnKierros125Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="kierrosRatkonta", Storage="_KierrosRatkonta", DbType="Int")]
		public System.Nullable<int> KierrosRatkonta
		{
			get
			{
				return this._KierrosRatkonta;
			}
			set
			{
				if ((this._KierrosRatkonta != value))
				{
					this.OnKierrosRatkontaChanging(value);
					this.SendPropertyChanging();
					this._KierrosRatkonta = value;
					this.SendPropertyChanged("KierrosRatkonta");
					this.OnKierrosRatkontaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="finaaliKierros", Storage="_FinaaliKierros", DbType="Int")]
		public System.Nullable<int> FinaaliKierros
		{
			get
			{
				return this._FinaaliKierros;
			}
			set
			{
				if ((this._FinaaliKierros != value))
				{
					this.OnFinaaliKierrosChanging(value);
					this.SendPropertyChanging();
					this._FinaaliKierros = value;
					this.SendPropertyChanged("FinaaliKierros");
					this.OnFinaaliKierrosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="finaaliRatkonta", Storage="_FinaaliRatkonta", DbType="Int")]
		public System.Nullable<int> FinaaliRatkonta
		{
			get
			{
				return this._FinaaliRatkonta;
			}
			set
			{
				if ((this._FinaaliRatkonta != value))
				{
					this.OnFinaaliRatkontaChanging(value);
					this.SendPropertyChanging();
					this._FinaaliRatkonta = value;
					this.SendPropertyChanged("FinaaliRatkonta");
					this.OnFinaaliRatkontaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="seuraID", Storage="_SeuraID", DbType="Int NOT NULL")]
		public int SeuraID
		{
			get
			{
				return this._SeuraID;
			}
			set
			{
				if ((this._SeuraID != value))
				{
					this.OnSeuraIDChanging(value);
					this.SendPropertyChanging();
					this._SeuraID = value;
					this.SendPropertyChanged("SeuraID");
					this.OnSeuraIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="joukkueID", Storage="_JoukkueID", DbType="Int")]
		public System.Nullable<int> JoukkueID
		{
			get
			{
				return this._JoukkueID;
			}
			set
			{
				if ((this._JoukkueID != value))
				{
					this.OnJoukkueIDChanging(value);
					this.SendPropertyChanging();
					this._JoukkueID = value;
					this.SendPropertyChanged("JoukkueID");
					this.OnJoukkueIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="sarjaID", Storage="_SarjaID", DbType="Int")]
		public System.Nullable<int> SarjaID
		{
			get
			{
				return this._SarjaID;
			}
			set
			{
				if ((this._SarjaID != value))
				{
					this.OnSarjaIDChanging(value);
					this.SendPropertyChanging();
					this._SarjaID = value;
					this.SendPropertyChanged("SarjaID");
					this.OnSarjaIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="era", Storage="_Era", DbType="NVarChar(100)")]
		public string Era
		{
			get
			{
				return this._Era;
			}
			set
			{
				if ((this._Era != value))
				{
					this.OnEraChanging(value);
					this.SendPropertyChanging();
					this._Era = value;
					this.SendPropertyChanged("Era");
					this.OnEraChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute()]
	public partial class Sarja : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _SarjaID;
		
		private string _Sarja1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSarjaIDChanging(int value);
    partial void OnSarjaIDChanged();
    partial void OnSarja1Changing(string value);
    partial void OnSarja1Changed();
    #endregion
		
		public Sarja()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="sarjaID", Storage="_SarjaID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int SarjaID
		{
			get
			{
				return this._SarjaID;
			}
			set
			{
				if ((this._SarjaID != value))
				{
					this.OnSarjaIDChanging(value);
					this.SendPropertyChanging();
					this._SarjaID = value;
					this.SendPropertyChanged("SarjaID");
					this.OnSarjaIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="sarja", Storage="_Sarja1", DbType="NVarChar(100)")]
		public string Sarja1
		{
			get
			{
				return this._Sarja1;
			}
			set
			{
				if ((this._Sarja1 != value))
				{
					this.OnSarja1Changing(value);
					this.SendPropertyChanging();
					this._Sarja1 = value;
					this.SendPropertyChanged("Sarja1");
					this.OnSarja1Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute()]
	public partial class Seura : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _SeuraID;
		
		private string _Seura1;
		
		private string _Lyhenne;
		
		private string _Alue;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSeuraIDChanging(int value);
    partial void OnSeuraIDChanged();
    partial void OnSeura1Changing(string value);
    partial void OnSeura1Changed();
    partial void OnLyhenneChanging(string value);
    partial void OnLyhenneChanged();
    partial void OnAlueChanging(string value);
    partial void OnAlueChanged();
    #endregion
		
		public Seura()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="seuraID", Storage="_SeuraID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int SeuraID
		{
			get
			{
				return this._SeuraID;
			}
			set
			{
				if ((this._SeuraID != value))
				{
					this.OnSeuraIDChanging(value);
					this.SendPropertyChanging();
					this._SeuraID = value;
					this.SendPropertyChanged("SeuraID");
					this.OnSeuraIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="seura", Storage="_Seura1", DbType="NVarChar(100)")]
		public string Seura1
		{
			get
			{
				return this._Seura1;
			}
			set
			{
				if ((this._Seura1 != value))
				{
					this.OnSeura1Changing(value);
					this.SendPropertyChanging();
					this._Seura1 = value;
					this.SendPropertyChanged("Seura1");
					this.OnSeura1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="lyhenne", Storage="_Lyhenne", DbType="NVarChar(100)")]
		public string Lyhenne
		{
			get
			{
				return this._Lyhenne;
			}
			set
			{
				if ((this._Lyhenne != value))
				{
					this.OnLyhenneChanging(value);
					this.SendPropertyChanging();
					this._Lyhenne = value;
					this.SendPropertyChanged("Lyhenne");
					this.OnLyhenneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="alue", Storage="_Alue", DbType="NVarChar(100)")]
		public string Alue
		{
			get
			{
				return this._Alue;
			}
			set
			{
				if ((this._Alue != value))
				{
					this.OnAlueChanging(value);
					this.SendPropertyChanging();
					this._Alue = value;
					this.SendPropertyChanged("Alue");
					this.OnAlueChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
